### ISSUE TITLE
/etc/hosts

### ISSUE THREAD

**Issue by bbn** [hoodiehq-archive/local-tld#17]
the rules I have set up in /etc/hosts don't work after installing local-tld.

if I "sudo ipfw flush" then they all work again.

OS X 10.8.3

sadly local-tld has been nothing but problems for me. :(

**Comment by sallespromanager** [comment]
hi, i am having such a problem too.

i installed local-tld successfully and i can run the hoodie starndard app too.

the problem is my local web server is neither being capable of responding to previously configured /etc/hosts nor to 127.0.0.1.

how can we deal with this ? how can i DISABLE or uninstall local-tld ?

**Comment by hazeledmands** [comment]
You should be able to disable local-tld by running `npm rm -g local-tld` -- that will run a script that should set your network settings back to the way they were before.

**Comment by hazeledmands** [comment]
Actually, the uninstall script doesn't flush your ipfw settings. @bbn's `sudo ipfw flush` should work, or if you want you can run `sudo ipfw list` and then `sudo ipfw delete <number>` where `<number>` is the number of the rule that looks like this:

`<number> fwd 127.0.0.1,5999 tcp from any to me dst-port 80 in`

**Comment by sallespromanager** [comment]
great. thanks for the quick reply.

Is there anyway to keep it dealing with the subdomains only ? Or just do the redirection for 600x ports instead of messing up with port 80 ?

i tried to include my root domain into `~/.local-tld.json` but it didnt work.

**Comment by janl** [comment]
It’s the trade-off you need to make: use local-tld and get nice URLs without ports, but don’t get any other service going on port 80.

local-tld always needs to take over port 80, otherwise you can just use port numbers to differentiate.

Note that Hoodie doesn’t require local-tld any more, so you can just nuke it and still use Hoodie.
